# Generated by Django 5.2.1 on 2025-06-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_technicalcompetency_codingquestion_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingquestion',
            name='competency',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='question',
        ),
        migrations.DeleteModel(
            name='TechnicalCompetency',
        ),
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
    ]
