# Generated by Django 5.0.2 on 2025-03-18 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('skill_category', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('time_limit', models.IntegerField()),
                ('skill_weights', models.JSONField(default=dict)),
                ('learning_objectives', models.JSONField(default=list)),
                ('prerequisites', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('response_text', models.TextField()),
                ('skills_demonstrated', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_competency_test.questionanalytics')),
            ],
        ),
    ]
