# Generated by Django 5.0.2 on 2025-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_competency_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.CreateModel(
            name='ProjectScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_sector', models.CharField(max_length=100)),
                ('scenario_type', models.CharField(choices=[('TECHNICAL', 'Technical Challenge'), ('ARCHITECTURE', 'System Architecture'), ('PROCESS', 'Process Improvement'), ('STAKEHOLDER', 'Stakeholder Management'), ('COMPLIANCE', 'Compliance & Security')], max_length=50)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technical_context', models.JSONField()),
                ('business_context', models.JSONField()),
                ('stakeholders', models.JSONField()),
                ('constraints', models.JSONField()),
                ('success_criteria', models.JSONField()),
                ('required_skills', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_scenarios',
                'indexes': [models.Index(fields=['industry_sector'], name='project_sce_industr_53155d_idx'), models.Index(fields=['scenario_type'], name='project_sce_scenari_50961d_idx'), models.Index(fields=['difficulty_level'], name='project_sce_difficu_462db0_idx')],
            },
        ),
        migrations.DeleteModel(
            name='QuestionAnalytics',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
