# Generated by Django 5.2.1 on 2025-06-11 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hr_user_id', models.UUIDField()),
                ('organization_name', models.CharField(max_length=255)),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('employee_count', models.IntegerField(default=0)),
                ('overall_competency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_technical_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_soft_skill_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_domain_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_sop_coverage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('team_analytics', models.JSONField(blank=True, default=dict)),
                ('employee_summary', models.JSONField(blank=True, default=dict)),
                ('critical_gaps', models.JSONField(blank=True, default=dict)),
                ('skill_category_breakdown', models.JSONField(blank=True, default=dict)),
                ('custom_metrics', models.JSONField(blank=True, default=dict)),
                ('trend_data', models.JSONField(blank=True, default=dict)),
                ('benchmark_data', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
                ('data_freshness', models.DateTimeField(blank=True, null=True)),
                ('computation_metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Analytics',
                'verbose_name_plural': 'HR Analytics',
                'db_table': 'hr_analytics',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Personnel',
                'verbose_name_plural': 'HR Personnel',
                'db_table': 'hr_personnel',
            },
        ),
        migrations.CreateModel(
            name='HRAnalyticsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hr_user_id', models.UUIDField()),
                ('organization_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('job_type', models.CharField(choices=[('full_analysis', 'Full Analysis'), ('incremental', 'Incremental Update'), ('refresh', 'Data Refresh')], default='full_analysis', max_length=20)),
                ('employees_processed', models.IntegerField(default=0)),
                ('total_employees', models.IntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_log', models.JSONField(blank=True, default=dict)),
                ('job_parameters', models.JSONField(blank=True, default=dict)),
                ('performance_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_analytics.hranalytics')),
            ],
            options={
                'verbose_name': 'HR Analytics Job',
                'verbose_name_plural': 'HR Analytics Jobs',
                'db_table': 'hr_analytics_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRAnalyticsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('config_type', models.CharField(choices=[('thresholds', 'Thresholds'), ('weights', 'Weights'), ('kpis', 'KPIs'), ('display', 'Display'), ('notifications', 'Notifications')], max_length=20)),
                ('config_name', models.CharField(max_length=100)),
                ('config_value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_analytics.hranalyticsconfig')),
            ],
            options={
                'verbose_name': 'HR Analytics Configuration',
                'verbose_name_plural': 'HR Analytics Configurations',
                'db_table': 'hr_analytics_config',
                'unique_together': {('organization_name', 'config_type', 'config_name', 'is_active')},
            },
        ),
    ]
